### ISSUE TITLE
Adding bitmap text

### ISSUE THREAD

**Issue by shohan4556** [orange-games/phaser-responsive#1]
Hi, I want to add bitmap text to the topleft using this plugin. so is it possible if possible please let me know how to do it.
thanks for the nice work.

**Comment by AleBles** [comment]
I added BitmapText support, so it should be possible now. But everything is calculated from the top left corner by default, so I'm not sure what this Library would add for you

**Comment by shohan4556** [comment]
I did not found any bitmap method in your code instead of found text support.
how can I use this code using the plugin  **bmpText = game.add.bitmapText(200, 100, 'desyrel', 'Phaser & Pixi\nrocking!', 64);**
I tried several way but it was throwing error.
