### ISSUE TITLE
how to use this in the typescript project 

### ISSUE THREAD

**Issue by metasong** [orange-games/phaser-responsive#4]
my project is webpack +typescript
when i try to import this package 
import \* as Responsiveness 'phaser-responsive/build/phaser-responsive';
error saids phaser-responsive.d.ts is not a module, please contact the author to update the definition.

**Comment by AleBles** [comment]
Yes that's a webpacky thing as described here: https://github.com/orange-games/phaser-input/pull/9

I indeed don't export any modules, so if you want that you should shim it as documented by webpack over here: https://webpack.github.io/docs/shimming-modules.html
